spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mall_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

# dubbo
dubbo:
  application:
    name: octopus-service
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    port: -1
    name: dubbo
  scan:
    base-packages: com.sourcecode.balant.octopus.biz.service
  provider:
    filter: -exception
    ActionService:
      version: 1.0.0
  consumer:
    filter: -exception
    UserService:
      version: 1.0.0



# logging
logging:
  level:
    # dao 开启 debug 模式 mybatis 输入 sql
    com.sourcecode.balant.octopus.biz: debug


